### PR TITLE
Design Home Page

### PR DESCRIPTION
**Pull request by chrismohrii**
Uses MD Bootstrap elements to show visuals from perspectiveapi.com, a mission statement, and grouped cards that link to each of the different modules. I'm certainly not a designer, feel free to suggest style or other changes!

image
image
image

### CODE REVIEW

**Review by danieldortega77 — APPROVED** [review]
LGTM! If there's one thing, we might want to add some padding to the docs/sheets images, as they're very close to the border of the white background. But that's up to personal preference.

**Comment by olu144** [comment]
LGTM - It seems you have used some cool new fonts. Is this a change we want through out the website?

**Review by olu144 — APPROVED** [review]

**Comment by chrismohrii** [comment]
> LGTM! If there's one thing, we might want to add some padding to the docs/sheets images, as they're very close to the border of the white background. But that's up to personal preference.

I'll look into this - I think it's a little hard because of the way MDBootstrap cards are set up

**Comment by chrismohrii** [comment]
> LGTM - It seems you have used some cool new fonts. Is this a change we want through out the website?

Yes, I just used the default fonts from MDBootstrap. Once all pages are updated with MDBootstrap, this change will happen automatically

**Review by dslucas — APPROVED** [review]

**Review by dborkan — APPROVED** [review]
Looks good!

**Pull request merged**
